Revert "ANDROID: sched: Add vendor hook for update_load_sum"
This reverts commit 984523c368423410bf53ca4c68402897d160c5dd, removing the following undeclared
identifier:

../kernel/sched/pelt.c: In function '___update_load_sum':
../kernel/sched/pelt.c:209:56: error: 'sched_pelt_lshift' undeclared (first use in this function); did you mean 'sched_set_fifo'?
  209 |         trace_android_rvh_update_load_sum(sa, &delta, &sched_pelt_lshift);
      |                                                        ^~~~~~~~~~~~~~~~~
      |                                                        sched_set_fifo

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>